### ISSUE TITLE
Flash controller 

### ISSUE THREAD

**Issue by danielitzahi** [ZipCPU/icozip#6]
![20230921_103408](https://github.com/ZipCPU/icozip/assets/59854753/3f8d6c08-a755-4c7f-aed3-76fae1b89a0a)

Hi dan
How are you? 
I'm very happy about your site zipcpu
I had success with the flash controller :) It works with hello sample I used spixscop to debug
My next question is whether after writing the software into the flash why after cpu reset or fpga reset (button)  hello sample not running on boot.   best regards
Tzahi

_Originally posted by @danielitzahi in https://github.com/ZipCPU/icozip/issues/5#issuecomment-2182074563_

**Comment by danielitzahi** [comment]
By the way,
when I debugged the flashid, I saw a wake-up message being sent.
Is this implemented in the flashdriver inside the fpga
tzahi

**Comment by ZipCPU** [comment]
Check the "ZIP_START_HALTED" parameter.  If set to one, the design will start up in a halted configuration.

I'm not sure what you are describing as a "wakeup message".  You might need to tell me more for me to understand.

Dan

**Comment by danielitzahi** [comment]
Hi dan
Thanks for your response 
Befor you make the id request from the flash
In flashid.cpp
I add one more write

![Screenshot_20240621_185909_Chrome](https://github.com/ZipCPU/icozip/assets/59854753/f23935aa-3351-451d-a519-6083e94f36be)

Send "AB"command to flash
I attached picture from my flash datasheet 
Tzahi

**Comment by ZipCPU** [comment]
Ok, so ... you modified flashid.cpp to add an 8'hAB command?  Okay, so ... what then happened?  How did this work out for you?  Did the flash start working, or was there no difference?

I had thought you were asking about extraneous commands to the flash, and so I was expecting to need to chase things down.  In this case, it looks like you are sending a message to the flash and ... I haven't yet heard the end of the story.

Dan

**Comment by danielitzahi** [comment]
Hi dan
The flashid.cpp work after that.
And my questions is what we going todo 
On the start up after the fpga done who send this command
You don't have the flashid sw
Tzahi

**Comment by danielitzahi** [comment]
Hi dan
Extra information 
I can't communicate with the flash without 
This command
After that i run flashid.cpp
(Only one time after rest the board)
The hello sw work
But when i run the hello sw without flashid.cpp
Doesn't work

**Comment by danielitzahi** [comment]
Thanks again dan
I appreciate that

**Comment by ZipCPU** [comment]
Are you using an ICO board, or some other board?

Many of the flash chips I have require a startup sequence.  The spixpress IP in this repo doesn't use such a sequence in the interest of minimal area--especially since most flash chips don't require it when using SPI mode.  Two others flash controllers I have do require a startup sequence.  These are the dualflexpress (Dual SPI), and qflexpress (Quad SPI) controllers.  These can be programmed to issue a 0xab (or any other command for that matter) on startup.  This becomes a requirement if the loader, or whatever loads your flash config to the board, doesn't leave the flash in a usable state--as sounds like you are dealing with.

One solution might be to place the ZipCPU program in block RAM, and then use it to send the correct command to the flash--just like flashid.cpp does.  Once done, you can then jump to the appropriate flash address to continue.

Dan

**Comment by danielitzahi** [comment]
Hi dan
This is the board that i am using 
![20230921_103408](https://github.com/ZipCPU/icozip/assets/59854753/f48e17d1-5b26-4253-a99f-6ba29a74e98e)
Same fpga as ico board
Same sram size maybe diff
Of course  my board doesn't have all the pi/flash switches 
Tzahi

**Comment by ZipCPU** [comment]
My best guess is that this problem is associated with how your FPGA loader writes to the flash.  That's not something that's going to be common with the ICO board.

Try seeing what happens following a power cycle.  Does the FPGA automatically start from flash?  Does the ZipCPU automatically start running?

**Comment by danielitzahi** [comment]
Hi dan
My fpga loader sw write only to flash
After power/reset the ice loaded by flash by the internal lattice core
I am going to test this:
**
Try seeing what happens following a power cycle. Does the FPGA automatically start from flash? Does the ZipCPU automatically start running?
**
Thanks

**Comment by ZipCPU** [comment]
I'm going to close this issue, since it doesn't appear to be an issue with ICOZip -- which doesn't have this problem.

**Comment by danielitzahi** [comment]
Hi dan
The cpu run ok after reset command from dbg screen "run hello" from flash.
The only problem is on reset power or reset button
Work only after flashid with special command.

It possible to continue the conversation
In repo "qspiflash" ?
Tzahi

**Comment by ZipCPU** [comment]
You can continue it here if you'd like, it's just not an "issue" of the ICOZip repository.

**Comment by ZipCPU** [comment]
... and reset button is not relevant.  I'm interested in what happens after the flash and FPGA together get restarted from a power up, not what happens following a reset button of any type.

**Comment by danielitzahi** [comment]
Hi dan
After power reset the cpu live with blink Z
But hello no run.
As soon as I run flashid & send cpu reset comand
hello run ok
Tzahi

**Comment by danielitzahi** [comment]
I try manually after reset power
wdregs flashcfg 0xab
wdregs flashcfg 0x100
Reset cpu
Work..

Tzahi

**Comment by ZipCPU** [comment]
Well, there are two potential solutions as I see things.

1. You can have the CPU ...
  - Pre-load the block RAM with a hex file
  - Set the CPU to boot from block RAM
  - Execute the flash instructions you require
  - Then jump to your starting address in the flash, or ...
2. You could switch flash drivers to one that includes a startup script

Dan

**Comment by danielitzahi** [comment]
Hi dan
i prrefer choise number 1.
But I have a question for you
from a beginner student,
according to what i know we use the bram and you load it from the flash on power on.
So the loading suppose to delete pre-load file (am i right ?)
Tzahi

**Comment by ZipCPU** [comment]
The block RAM can be loaded any time the bitfile / configuration is loaded.  If the bitfile comes loaded with a program in block RAM, and if the reset pointer points there, then the CPU will start running instructions from that point.

This isn't a great general purpose solution, however, since block RAM tends to be so small that you can't do much with it.  However, it is big enough to load a program like this into it.

Another problem you may find with this solution is that the RAM will need to be reloaded any time you wish to hit a reset button (assuming you have a CPU reset separate from an FPGA reconfigure).  This would send the CPU to the reset address, which might be the (now overwritten) block RAM.  There are two solutions to this: 1) you could adjust your linker script so that any block RAM used would set the first block RAM word to jump to the top of the flash.  Once the flash is running, there'd be no problems with just jumping to the code in the flash.  2) Alternatively, you could just reload the FPGA any time you wished to reset the CPU.  3) If everything works as it should, zipload should still work as desired.

Dan

**Comment by ZipCPU** [comment]
I just came across another solution I've used over the years--booting from a small ROM.  I'll typically use the same memory device as the ROM, however, there is a setting you can use to indicate this.  A memdev.v with OPT_ROM=1 will turn it into a ROM.  You can still load it with a hex file as before, but this time the hex file can't be changed, and so all subsequent reboots of the CPU will use the same logic as is in that ROM file.

**Comment by danielitzahi** [comment]
hi Dan
I am still little bit not understand ):
sorry about that.
we already use memdev.v as bkram in the project so ..
if we going to change it to ROM,
after power on The bootloader from the flash fail to write the ".kernel" to bkram.
according to ld file:
""
       _kram_start = . ;
       .kernel : ALIGN_WITH_INPUT {
		*(.kernel)
		}> bkram AT> flash
""
should i need to pass ".kernel" to the sram section
Tzahi

**Comment by ZipCPU** [comment]
No, don't change the block RAM device to ROM.  Rather, make a second block RAM device, call it bkrom if you like.  Normally, I'd do this via AutoFPGA, by creating a "bkrom.txt" file, and adding the lines:

    @PREFIX=bkrom
    @DEVID=BKROM
    @INCLUDEFILE=bkram.txt
    @LD.PERM=rx
    @REGS.0=0 R_@$(DEVID) ROM

and then any other changes that might be required--such as overriding the @MAIN.INSERT tag to now have .OPT_ROM(1) in the parameter list together with a reference to the hex file containing the startup code, `.HEXFILE("URSTARTUP.hex")`.  You might also wish to clear the @SIM.DEFINES and @SIM.LOAD tags.  The final change would be to adjust the ZipCPU reset address to point to the ROM address.  This might be done by adjusting the `localparam RESET_ADDRESS` so that it now points to `@$(/bkrom.REGBASE)`.

Once done, all you'll have left to do will be to define your startup.hex file and test.

Dan

**Comment by danielitzahi** [comment]
Yessir
I am going to test this
By the way do i need to use special .hex file format.
I Search in your repo and i found something.
Tzahi

**Comment by ZipCPU** [comment]
You can find a utility you can use to make a hex file from a ZipCPU binary executable here:

https://github.com/ZipCPU/zipcpu/blob/master/sim/verilator/mkhex.cpp

You may need to adjust the addresses within here to point to the base address of your ROM before compiling.

**Comment by danielitzahi** [comment]
Hello Dan,
how are you? 
You asked me to make a boot rom .hex that includes an initialize sequence for the flash,
of course I did it, it works great, the card boot properly after power reset.
Thanks 🙏

**Comment by danielitzahi** [comment]
Dan,
By the way, a general question about the bkrom linker script, is it possible to integrate the bkram memory into it ? 
Is it true that only the .bss section can be used as ram memory in the bkrom program
because in my case i don't have a boot loader in the program to copy ather section do i understand correctly ?
Tzahi

**Comment by ZipCPU** [comment]
> By the way, a general question about the bkrom linker script, is it possible to integrate the bkram memory into it ?

Yes, of course.

> Is it true that only the .bss section can be used as ram memory in the bkrom program

.bss should not be used for ROM memory.

> ... do i understand correctly ?

If so, I'm not (yet) convinced.

Dan
